### ISSUE TITLE
Duplicate "Code" toolbar button added OOTB

### ISSUE THREAD

**Issue by klonos** [quicksketch/ckeditor5#12]
These are the default enabled/available buttons OOTB, when enabling CKEditor 5 as the editor for a new format:
<img src="https://github.com/quicksketch/ckeditor5/assets/2423362/e9688a24-7879-4c37-8a7c-a91c01ff2189" width=50%>

The code button is being added twice ^^

**Comment by quicksketch** [comment]
Thanks @klonos! Turns out this was actually a different button. It's "CodeBlock" vs. "Code" (inline). I incorrectly had them both pointing to just `code.svg` instead of the second `code-block.svg`. Fixed in https://github.com/quicksketch/ckeditor5/pull/26.
