### ISSUE TITLE
Autoformat doesn't work

### ISSUE THREAD

**Issue by klonos** [quicksketch/ckeditor5#19]
As per #6, the autoformat feature should be enabled:

> I've bundled the [CKEditor 5 Autoformat plugin](https://ckeditor.com/docs/ckeditor5/latest/features/autoformat.html) and enabled it by default. ...

I couldn't get it to work though. I have tried typing dashes/asterisks forllowed by spaces, but they didn't get converted to lists. Neither did wrapping text with asterisks/underscores work, nor hastags for headings etc.

Do I need to enable something in order to allow that? Have I missed something?

**Comment by quicksketch** [comment]
Thanks, @klonos! I messed something up when I was rearranging how dependencies were getting loaded. This has been fixed in https://github.com/quicksketch/ckeditor5/pull/23.
