### ISSUE TITLE
Add support for contextual toolbar balloon for tables

### ISSUE THREAD

**Issue by klonos** [quicksketch/ckeditor5#21]
https://ckeditor.com/docs/ckeditor5/latest/features/tables/tables.html#table-contextual-toolbar

> Use the insert table button Insert table to insert a new table into the content. Click inside the table to open a contextual toolbar. The toolbar lets you add or remove columns Table column and rows Table row. You can also merge or split cells Table cell.

![image](https://github.com/quicksketch/ckeditor5/assets/2423362/5f6a5307-4c47-49ff-93f4-b021c97369d5)

**Comment by quicksketch** [comment]
Thanks @klonos! Looks like another issue where dependencies weren't getting loaded. I fixed this in https://github.com/quicksketch/ckeditor5/pull/25 and now the table toolbar shows up. The table dependencies had already been specified in `ckeditor_ckeditor_plugins()`, they just weren't getting loaded.
