### ISSUE TITLE
PHP warnings when adding a CKE5-enabled filter

### ISSUE THREAD

**Issue by klonos** [quicksketch/ckeditor5#29]
Just wanted to quickly capture these in an issue for now - I will confirm whether they are specific to the PHP version or not:
```
- Warning: Undefined array key "style" in ckeditor5_settings_form_validate()
  (line 119 of /app/docroot/modules/ckeditor5/ckeditor5.admin.inc).
- Warning: Trying to access array offset on value of type null in ckeditor5_settings_form_validate()
  (line 119 of /app/docroot/modules/ckeditor5/ckeditor5.admin.inc).
- Deprecated function: explode(): Passing null to parameter #2 ($string) of type string is deprecated in
  _ckeditor5_settings_parse_style_list() (line 159 of /app/docroot/modules/ckeditor5/ckeditor5.admin.inc).
```

The above is when simply adding a new text format with all settings left to their default.

**Comment by klonos** [comment]
...the last deprecation warning about `explode()` is specific to PHP 8.1, but not the other warnings.

@quicksketch PR up for review here: https://github.com/quicksketch/ckeditor5/pull/30

**Comment by quicksketch** [comment]
Thanks @klonos! I moved the styles and heading list settings from `$editor_settings['plugin']['style']['style_list']` to just `$editor_settings['style_list']`, but looks like I missed a spot. Thanks for the PR!
